import { AuthService } from './auth/auth.js';
import { roleName } from './auth/permissions.js';
import { loadDatabase, saveDatabase } from './core/storage.js';
import { warehousePage, bindWarehouse, inventoryV2 } from './warehouse.js';

const NAV=[['warehouse','Склад FBS','warehouse.view'],['inventory','Учет склада','inventory.view'],['deliveries','Заявки на поставки','deliveries.view'],['transfers','Заявка на перемещение','transfers.view'],['revisions','Ревизия','revisions.view'],['nomenclature','Учет номенклатуры','nomenclature.view']];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={db:loadDatabase(),page:'warehouse'};const auth=new AuthService(state.db,()=>saveDatabase(state.db));
function user(){return auth.currentUser?{canEdit:auth.can('warehouse.edit'),isAdmin:auth.can('users.manage')}:null;}
export function startApp(root){window.addEventListener('storage',()=>{state.db=loadDatabase();render(root);});render(root);}
function render(root){if(!auth.currentUser){root.innerHTML=login();bindLogin(root);return;}if(!NAV.some(([k,,p])=>k===state.page&&auth.can(p)))state.page='warehouse';root.innerHTML=shell();const page=root.querySelector('#page');if(state.page==='warehouse')page.innerHTML=warehousePage(user());else if(state.page==='inventory')page.innerHTML=inventoryV2();else page.innerHTML=`<div class="empty card"><div class="empty-icon">${esc(state.page==='revisions'?'✓':'•')}</div><h2>${esc(NAV.find(x=>x[0]===state.page)?.[1])}</h2><p>Раздел будет подключён следующим этапом.</p></div>`;if(state.page==='warehouse')bindWarehouse(page,user(),()=>render(root));}
function login(){return `<main class="auth"><section class="auth-card"><div class="brand">B-JOB <span>FBS</span></div><h1>Вход в систему</h1><p class="muted">Платформа адресного хранения и сборки FBS</p><form id="loginForm"><label>Логин<input name="login" autocomplete="username" required autofocus></label><label>Пароль<input name="password" type="password" autocomplete="current-password" required></label><button class="primary wide">Войти</button><div id="loginError" class="error"></div></form></section></main>`;}
function shell(){const nav=NAV.filter(([, ,p])=>auth.can(p)).map(([k,l])=>`<button class="nav-item ${state.page===k?'active':''}" data-page="${k}">${l}</button>`).join('');return `<div class="app"><aside class="sidebar"><div class="brand">B-JOB <span>FBS</span></div><div class="user-card"><b>${esc(auth.currentUser.login)}</b><small>${roleName(auth.currentUser.role)}</small></div><nav>${nav}</nav><button id="logout" class="nav-item logout">Выйти</button></aside><main class="content"><header><div><h1>${esc(NAV.find(x=>x[0]===state.page)?.[1]||'B-JOB FBS')}</h1><p class="muted">${state.page==='warehouse'?'Проектирование и управление складами':state.page==='inventory'?'Автоматический учет содержимого':'Рабочий раздел FBS'}</p></div></header><section id="page" class="page"></section></main></div>`;}
function bindLogin(root){root.querySelector('#loginForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),r=auth.login(f.get('login'),f.get('password'));if(!r.ok)root.querySelector('#loginError').textContent=r.error;else render(root);};root.querySelector('#loginForm input')?.focus();}
document.addEventListener('click',e=>{const b=e.target.closest('[data-page]');if(b){state.page=b.dataset.page;render(document.getElementById('app'));}if(e.target.closest('#logout')){auth.logout();render(document.getElementById('app'));}});
