import { loadDatabase, saveDatabase, makeId } from './core/storage.js';

const KEY='bjob-fbs-warehouse-v2';
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY))||{warehouses:[],boxes:[]};}catch{return {warehouses:[],boxes:[]};}};
const write=db=>localStorage.setItem(KEY,JSON.stringify(db));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=p=>`${p}-${crypto.randomUUID().slice(0,8)}`;
const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
const rect=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
const db=()=>{const d=read();d.warehouses??=[];d.boxes??=[];return d;};
let warehouseId=null, setupStep=1, draftZone=null, drag=null, resize=null;

export function warehousePage(user,root){
 const d=db(); if(!warehouseId||!d.warehouses.some(w=>w.id===warehouseId)) warehouseId=d.warehouses[0]?.id||null;
 if(!warehouseId)return empty(user);
 const w=d.warehouses.find(x=>x.id===warehouseId);
 return w.status==='setup'?setup(w,user):map(w,user);
}
function empty(user){return `<div class="empty card"><div class="empty-icon">▦</div><h2>Складов пока нет</h2><p>Создайте свой первый склад.</p>${user.canEdit?'<button class="primary" data-w2-create>Создать склад</button>':''}</div>`;}
function setup(w,user){
 const names=['Комната склада','Вход и элементы','Рабочие пространства','Завершение'];
 const controls=setupStep===1?'<button class="tool" data-w2-add="room">□ Прямоугольник стен</button><button class="tool" data-w2-add="wall">╱ Внутренняя стена</button>':setupStep===2?'<button class="tool" data-w2-add="entrance">↪ Вход</button><button class="tool" data-w2-add="window">□ Окно</button><button class="tool" data-w2-add="gate">▣ Ворота</button><button class="tool" data-w2-add="partition">│ Перегородка</button>':setupStep===3?'<button class="tool" data-w2-add="work">▦ Сборка + упаковка</button><button class="tool" data-w2-add="empty">·· Пустые короба</button><button class="tool" data-w2-add="trash">·· Мусор</button>':'<div class="hint">Проверьте схему. После сохранения планировка фиксируется.</div>';
 return `<div class="wizard"><div class="steps">${names.map((n,i)=>`<div class="step ${setupStep===i+1?'current':''} ${setupStep>i+1?'done':''}"><b>${i+1}</b><span>${n}</span></div>`).join('')}</div><div class="card wizard-body"><div class="w2-head"><div><div class="eyebrow">Склад · ${esc(w.name)}</div><h2>Шаг ${setupStep}. ${names[setupStep-1]}</h2></div></div><div class="warehouse-canvas" data-w2-canvas>${(w.elements||[]).map(e=>element(e,e.step!==setupStep)).join('')}</div><div class="tool-row">${controls}</div><div class="wizard-actions">${setupStep>1?'<button class="secondary" data-w2-prev>Назад</button>':''}${setupStep<4?'<button class="primary" data-w2-next>Продолжить</button>':'<button class="primary" data-w2-finish>Сохранить планировку</button>'}</div></div></div>`;
}
function element(e,locked){return `<div class="canvas-element w2-el ${esc(e.type)} ${locked?'locked':''}" data-w2-el="${esc(e.id)}" style="left:${e.x}%;top:${e.y}%;width:${e.w}%;height:${e.h}%;transform:rotate(${e.r||0}deg)">${e.type==='entrance'?'':esc(e.label)}${!locked?'<button class="w2-el-del" data-w2-del="'+esc(e.id)+'">×</button><i class="w2-el-resize"></i>':''}</div>`;}
function map(w,user){const d=db(),boxes=d.boxes.filter(b=>b.warehouseId===w.id),zones=w.zones||[];return `<div class="w2-toolbar card"><div><div class="eyebrow">Склад FBS</div><h2>${esc(w.name)}</h2><span class="muted">${zones.length} зон · ${boxes.length} коробов</span></div><div class="w2-actions"><select class="warehouse-select" data-w2-select>${d.warehouses.map(x=>`<option value="${esc(x.id)}" ${x.id===w.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select>${user.canEdit?'<button class="secondary" data-w2-new>＋ Новый склад</button><button class="primary" data-w2-zone>＋ Разместить зону</button>':''}${user.isAdmin?'<button class="danger-button" data-w2-delete>Удалить склад</button>':''}<button class="secondary" data-w2-demo>Демонстрация склада</button></div></div><div class="w2-layout"><div class="w2-map card" data-w2-map>${(w.elements||[]).map(e=>element(e,true)).join('')}${zones.map(z=>zoneHtml(z,w,d)).join('')}</div><aside class="w2-side card"><h3>Склад</h3><div class="w2-stats"><div><b>${zones.length}</b><span>зон</span></div><div><b>${boxes.length}</b><span>ящиков</span></div></div><hr><h3>Зоны хранения</h3>${zones.length?zones.map(z=>`<div class="w2-zone-row"><div><b>${esc(z.name)}</b><small>${(z.boxIds||[]).length} / ${z.capacity} ящиков</small></div></div>`).join(''):'<p class="muted">Зоны пока не созданы.</p>'}</aside></div>`;}
function zoneHtml(z,w,d){const boxes=d.boxes.filter(b=>b.zoneId===z.id);return `<div class="w2-zone ${z.locked?'locked':''} ${draftZone===z.id?'editing':''}" data-w2-zone="${esc(z.id)}" style="left:${z.x}%;top:${z.y}%;width:${z.w}%;height:${z.h}%"><header><b>${esc(z.name)}</b><span>${boxes.length}/${z.capacity}</span></header><div class="w2-boxes">${boxes.map((b,i)=>`<button class="w2-box" data-w2-box="${esc(b.id)}"><b>Ящик ${i+1}</b><small>${esc(b.contents?.[0]?.article||'Пустой')}</small></button>`).join('')}</div>${draftZone===z.id?'<button class="w2-save-zone" data-w2-save-zone>Сохранить расположение</button><i class="w2-resize"></i>':'<button class="w2-add-box" data-w2-add-box="'+esc(z.id)+'">＋ Добавить ящик</button>'}</div>`;}

export function bindWarehouse(root,user,onChange){
 root.querySelector('[data-w2-create]')?.addEventListener('click',()=>createWarehouse(onChange));
 root.querySelector('[data-w2-new]')?.addEventListener('click',()=>createWarehouse(onChange));
 root.querySelector('[data-w2-select]')?.addEventListener('change',e=>{warehouseId=e.target.value;draftZone=null;onChange();});
 root.querySelector('[data-w2-delete]')?.addEventListener('click',()=>deleteWarehouse(onChange));
 root.querySelector('[data-w2-zone]')?.addEventListener('click',()=>createZone(onChange));
 root.querySelector('[data-w2-demo]')?.addEventListener('click',()=>demo(onChange));
 root.querySelector('[data-w2-prev]')?.addEventListener('click',()=>{setupStep--;onChange();});
 root.querySelector('[data-w2-next]')?.addEventListener('click',()=>{setupStep++;onChange();});
 root.querySelector('[data-w2-finish]')?.addEventListener('click',()=>finish(onChange));
 root.querySelectorAll('[data-w2-add]').forEach(b=>b.addEventListener('click',()=>addElement(b.dataset.w2Add,onChange)));
 root.querySelectorAll('[data-w2-del]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();deleteElement(b.dataset.w2Del,onChange)}));
 root.querySelectorAll('[data-w2-add-box]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();boxModal(b.dataset.w2AddBox,onChange)}));
 root.querySelectorAll('[data-w2-box]').forEach(b=>b.addEventListener('click',()=>boxModalView(b.dataset.w2Box,onChange)));
 root.querySelectorAll('[data-w2-save-zone]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();saveZone(b.closest('[data-w2-zone]').dataset.w2Zone,onChange)}));
 root.querySelectorAll('[data-w2-zone]').forEach(z=>{if(!z.classList.contains('locked')&&draftZone===z.dataset.w2Zone)makeDrag(z,root.querySelector('[data-w2-map]'),onChange);});
 root.querySelectorAll('[data-w2-zone] .w2-resize').forEach(h=>makeResize(h,root.querySelector('[data-w2-map]'),onChange));
}
function createWarehouse(onChange){const d=db();const name=prompt('Название склада',`Склад №${d.warehouses.length+1}`)?.trim();if(!name)return;const w={id:uid('wh'),name,status:'setup',elements:[],zones:[],createdAt:Date.now()};d.warehouses.push(w);write(d);warehouseId=w.id;setupStep=1;onChange();}
function deleteWarehouse(onChange){const d=db(),w=d.warehouses.find(x=>x.id===warehouseId);if(!w)return;const boxes=d.boxes.filter(b=>b.warehouseId===w.id);if(boxes.length){alert('На складе есть изделия. Верните изделия в учет перед удалением склада.');return;}if(!confirm(`Удалить склад «${w.name}»?`))return;d.warehouses=d.warehouses.filter(x=>x.id!==w.id);write(d);warehouseId=d.warehouses[0]?.id||null;onChange();}
function addElement(type,onChange){const d=db(),w=d.warehouses.find(x=>x.id===warehouseId);if(!w)return;const labels={room:'Стены',wall:'Внутренняя стена',entrance:'Вход',window:'Окно',gate:'Ворота',partition:'Перегородка',work:'Сборка и упаковка',empty:'Пустые короба',trash:'Мусор'};if(type==='entrance'&&(w.elements||[]).some(e=>e.type==='entrance'))return alert('Вход уже установлен.');const n=w.elements.length;w.elements.push({id:uid('el'),type,label:labels[type],step:setupStep,x:10+(n%4)*18,y:12+(n%4)*12,w:type==='wall'?28:22,h:type==='wall'?3:18});write(d);onChange();}
function deleteElement(id,onChange){const d=db(),w=d.warehouses.find(x=>x.id===warehouseId);w.elements=(w.elements||[]).filter(e=>e.id!==id);write(d);onChange();}
function finish(onChange){const d=db(),w=d.warehouses.find(x=>x.id===warehouseId);if(!(w.elements||[]).some(e=>e.type==='room'||e.type==='wall'))return alert('Создайте стены.');if(!(w.elements||[]).some(e=>e.type==='entrance'))return alert('Добавьте вход.');w.status='ready';write(d);onChange();}
function createZone(onChange){const d=db(),w=d.warehouses.find(x=>x.id===warehouseId);const name=prompt('Название зоны',`Зона ${String.fromCharCode(65+(w.zones?.length||0))}`)?.trim();if(!name)return;const capacity=Number(prompt('Вместимость зоны в ящиках','10'));if(!Number.isInteger(capacity)||capacity<1)return alert('Введите положительную вместимость.');const z={id:uid('zone'),name,capacity,boxIds:[],x:8,y:10,w:22,h:20,locked:false};w.zones.push(z);draftZone=z.id;write(d);onChange();}
function bounds(z,map){const walls=(db().warehouses.find(x=>x.id===warehouseId)?.elements||[]).find(e=>e.type==='room');if(!walls)return {x:0,y:0,w:100,h:100};return {x:walls.x,y:walls.y,w:walls.w,h:walls.h};}
function validZone(z,w,ignore){const b=bounds(z);if(z.x<b.x||z.y<b.y||z.x+z.w>b.x+b.w||z.y+z.h>b.y+b.h)return false;return !(w.zones||[]).some(o=>o.id!==ignore&&o.locked&&rect(z,o));}
function makeDrag(el,map,onChange){el.onpointerdown=e=>{if(e.target.closest('button')||e.target.classList.contains('w2-resize'))return;e.preventDefault();const r=map.getBoundingClientRect();drag={el,r,sx:parseFloat(el.style.left),sy:parseFloat(el.style.top),x:e.clientX,y:e.clientY};el.setPointerCapture(e.pointerId);};el.onpointermove=e=>{if(!drag||drag.el!==el)return;const d=db(),w=d.warehouses.find(x=>x.id===warehouseId),z=w.zones.find(x=>x.id===el.dataset.w2Zone),dx=(e.clientX-drag.x)/drag.r.width*100,dy=(e.clientY-drag.y)/drag.r.height*100,n={...z,x:drag.sx+dx,y:drag.sy+dy};if(validZone(n,w,z.id)){el.style.left=n.x+'%';el.style.top=n.y+'%';}};el.onpointerup=()=>{if(!drag)return;const d=db(),w=d.warehouses.find(x=>x.id===warehouseId),z=w.zones.find(x=>x.id===el.dataset.w2Zone);z.x=parseFloat(el.style.left);z.y=parseFloat(el.style.top);write(d);drag=null;};}
function makeResize(h,map,onChange){h.onpointerdown=e=>{e.preventDefault();e.stopPropagation();const el=h.closest('[data-w2-zone]'),r=map.getBoundingClientRect();resize={el,r,sx:parseFloat(el.style.width),sy:parseFloat(el.style.height),x:e.clientX,y:e.clientY};el.setPointerCapture(e.pointerId);};h.onpointermove=e=>{if(!resize||resize.el!==h.closest('[data-w2-zone]'))return;const zEl=resize.el,d=db(),w=d.warehouses.find(x=>x.id===warehouseId),z=w.zones.find(x=>x.id===zEl.dataset.w2Zone),nw=clamp(resize.sx+(e.clientX-resize.x)/resize.r.width*100,8,100-z.x),nh=clamp(resize.sy+(e.clientY-resize.y)/resize.r.height*100,8,100-z.y),n={...z,w:nw,h:nh};if(validZone(n,w,z.id)){zEl.style.width=nw+'%';zEl.style.height=nh+'%';}};h.onpointerup=()=>{if(!resize)return;const d=db(),w=d.warehouses.find(x=>x.id===warehouseId),z=w.zones.find(x=>x.id===resize.el.dataset.w2Zone);z.w=parseFloat(resize.el.style.width);z.h=parseFloat(resize.el.style.height);write(d);resize=null;};}
function saveZone(id,onChange){const d=db(),w=d.warehouses.find(x=>x.id===warehouseId),z=w.zones.find(x=>x.id===id);if(!validZone(z,w,id))return alert('Зона должна находиться внутри стен и не пересекать другие зоны.');z.locked=true;draftZone=null;write(d);onChange();}
function barcodeItem(query){const n=loadDatabase().nomenclature||[];return n.find(x=>String(x.barcode||x.barcodes?.[0]||'')===String(query).trim());}
function boxModal(zoneId,onChange){const d=db(),w=d.warehouses.find(x=>x.id===warehouseId),z=w.zones.find(x=>x.id===zoneId);if(z.boxIds.length>=z.capacity)return alert('Зона заполнена.');document.body.insertAdjacentHTML('beforeend',`<div class="w2-modal-backdrop" data-w2-modal><div class="w2-modal"><button class="w2-close" data-close>×</button><div class="eyebrow">${esc(z.name)}</div><h2>Добавить ящик</h2><button class="primary wide" data-scan>▣ Отсканировать ШК</button><button class="secondary wide" data-search>Поиск</button><div class="w2-search" hidden><input data-query placeholder="Артикул, размер или ШК"><div data-results></div></div><div data-selected class="w2-selected" hidden></div><label>Количество<input data-qty type="number" min="1" value="1"></label><button class="primary wide" data-save>Добавить ящик</button></div></div>`);const m=document.querySelector('[data-w2-modal]'),close=()=>m.remove();m.querySelector('[data-close]').onclick=close;let selected=null;const choose=x=>{selected=x;m.querySelector('[data-selected]').hidden=false;m.querySelector('[data-selected]').innerHTML=`<b>${esc(x.article||x.sellerArticle)}</b><span>Размер: ${esc(x.size)} · Цвет: ${esc(x.color||'—')} · ШК: ${esc(x.barcode)}</span>`;};m.querySelector('[data-scan]').onclick=()=>{const q=prompt('Введите или отсканируйте ШК');const x=q&&barcodeItem(q);if(x)choose(x);else if(q)alert('ШК не найден.');};m.querySelector('[data-search]').onclick=()=>{m.querySelector('.w2-search').hidden=false;m.querySelector('[data-query]').focus();};m.querySelector('[data-query]').oninput=e=>{const q=e.target.value.toLowerCase();const n=(loadDatabase().nomenclature||[]).filter(x=>[x.article,x.sellerArticle,x.size,x.color,x.barcode].some(v=>String(v||'').toLowerCase().includes(q))).slice(0,10);m.querySelector('[data-results]').innerHTML=n.map((x,i)=>`<button class="w2-result" data-i="${i}"><b>${esc(x.article||x.sellerArticle)}</b><span>${esc(x.size||'—')} · ${esc(x.color||'—')}</span></button>`).join('');m.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>choose(n[+b.dataset.i]));};m.querySelector('[data-save]').onclick=()=>{if(!selected)return alert('Выберите изделие.');const q=Number(m.querySelector('[data-qty]').value);if(!Number.isInteger(q)||q<1)return alert('Количество должно быть положительным.');const d2=db(),w2=d2.warehouses.find(x=>x.id===warehouseId),z2=w2.zones.find(x=>x.id===zoneId),seq=d2.boxes.length+1,b={id:uid('box'),warehouseId,zoneId,name:`Ящик ${String(seq).padStart(4,'0')}`,qr:`BJOB-${String(seq).padStart(6,'0')}`,contents:[{article:selected.article||selected.sellerArticle,barcode:selected.barcode,size:selected.size,color:selected.color,quantity:q}],createdAt:Date.now()};d2.boxes.push(b);z2.boxIds.push(b.id);write(d2);close();onChange();};}
function boxModalView(id,onChange){const d=db(),b=d.boxes.find(x=>x.id===id);if(!b)return;const c=b.contents?.[0]||{};document.body.insertAdjacentHTML('beforeend',`<div class="w2-modal-backdrop" data-w2-box-modal><div class="w2-modal"><button class="w2-close" data-close>×</button><div class="eyebrow">${esc(b.name)}</div><h2>${esc(c.article||'Ящик')}</h2><div class="w2-box-info"><span>Размер <b>${esc(c.size||'—')}</b></span><span>Цвет <b>${esc(c.color||'—')}</b></span><span>Количество <b>${c.quantity||0}</b></span><span>QR <b>${esc(b.qr)}</b></span></div><button class="secondary wide" data-revision>Добавить в ревизию</button><button class="secondary wide" data-move>Переместить</button><button class="secondary wide" data-print>Распечатать QR</button><button class="danger-button wide" data-remove>Удалить</button></div></div>`);const m=document.querySelector('[data-w2-box-modal]');m.querySelector('[data-close]').onclick=()=>m.remove();m.querySelector('[data-remove]').onclick=()=>{if(confirm('Удалить ящик? Остаток автоматически исчезнет из учета склада.')){const d2=db(),b2=d2.boxes.find(x=>x.id===id),w=d2.warehouses.find(x=>x.id===b2.warehouseId),z=w.zones.find(x=>x.id===b2.zoneId);z.boxIds=(z.boxIds||[]).filter(x=>x!==id);d2.boxes=d2.boxes.filter(x=>x.id!==id);write(d2);m.remove();onChange();}};m.querySelector('[data-revision]').onclick=()=>{b.revisionRequested=true;write(d);alert('Ящик добавлен в список ревизии.');};m.querySelector('[data-move]').onclick=()=>moveBox(id,m,onChange);m.querySelector('[data-print]').onclick=()=>printQr(b);}
function moveBox(id,m,onChange){const d=db(),b=d.boxes.find(x=>x.id===id),w=d.warehouses.find(x=>x.id===b.warehouseId),available=w.zones.filter(z=>z.id!==b.zoneId&&z.boxIds.length<z.capacity);m.querySelector('.w2-modal').innerHTML=`<button class="w2-close" data-close>×</button><h2>Переместить ящик</h2>${available.map(z=>`<button class="w2-result" data-move-zone="${z.id}"><b>${esc(z.name)}</b><span>${z.boxIds.length}/${z.capacity}</span></button>`).join('')||'<p class="muted">Нет свободных зон.</p>'}`;m.querySelector('[data-close]').onclick=()=>m.remove();m.querySelectorAll('[data-move-zone]').forEach(x=>x.onclick=()=>{const d2=db(),b2=d2.boxes.find(y=>y.id===id),w2=d2.warehouses.find(y=>y.id===b2.warehouseId),old=w2.zones.find(z=>z.id===b2.zoneId),nw=w2.zones.find(z=>z.id===x.dataset.moveZone);old.boxIds=old.boxIds.filter(y=>y!==id);nw.boxIds.push(id);b2.zoneId=nw.id;write(d2);m.remove();onChange();});}
function printQr(b){const html=`<!doctype html><html><head><title>${esc(b.name)}</title><style>@page{size:58mm 60mm;margin:0}html,body{width:58mm;height:60mm;margin:0;font-family:Arial,sans-serif}body{display:flex;align-items:center;justify-content:center}.label{text-align:center;width:54mm}.qr{font-size:26pt;font-weight:700;border:1px solid #000;padding:5mm 2mm;margin:3mm 0}</style></head><body><div class="label"><b>B-JOB FBS</b><div>${esc(b.name)}</div><div class="qr">${esc(b.qr)}</div><small>Сканируйте QR</small></div><script>window.print()<\/script></body></html>`;const w=window.open('','_blank','width=300,height=350');if(w){w.document.write(html);w.document.close();}}
function demo(onChange){const d=db(),w=d.warehouses.find(x=>x.id===warehouseId);document.body.insertAdjacentHTML('beforeend',`<div class="w2-demo"><button class="w2-demo-close" data-close-demo>×</button><div class="w2-demo-head"><b>${esc(w.name)}</b><span>Демонстрация склада</span></div><div class="w2-demo-map">${(w.elements||[]).map(e=>element(e,true)).join('')}${(w.zones||[]).map(z=>`<div class="w2-zone demo-zone" style="left:${z.x}%;top:${z.y}%;width:${z.w}%;height:${z.h}%"><b>${esc(z.name)}</b><span>${(z.boxIds||[]).length} ящиков</span></div>`).join('')}</div></div>`);document.querySelector('[data-close-demo]').onclick=()=>document.querySelector('.w2-demo')?.remove();}

export function inventoryV2(){const d=db();const rows=[];for(const b of d.boxes){for(const c of b.contents||[]){rows.push(`<tr><td>${esc(c.barcode)}</td><td>${esc(c.article)}</td><td>${esc(c.size)}</td><td>${esc(c.color||'')}</td><td>${esc(d.warehouses.find(w=>w.id===b.warehouseId)?.zones.find(z=>z.id===b.zoneId)?.name||'Без зоны')}</td><td><b>${Number(c.quantity)||0}</b></td></tr>`);}}return `<div class="card table-card"><div class="table-head"><div><h2>Учет склада</h2><p class="muted">Автоматический учет. Формируется из содержимого коробов.</p></div></div><table><thead><tr><th>Баркод</th><th>Артикул продавца</th><th>Размер</th><th>Цвет</th><th>Зона</th><th>Количество</th></tr></thead><tbody>${rows.length?rows.join(''):'<tr><td colspan="6" class="empty-cell">Учет пуст.</td></tr>'}</tbody></table></div>`;}
export function setWarehouseV2(id){warehouseId=id;setupStep=1;draftZone=null;}
