const DB_KEY='bjob-fbs-db-v1';
const SESSION_KEY='bjob-fbs-session-v1';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=p=>`${p}_${globalThis.crypto?.randomUUID?.().slice(0,8)||Math.random().toString(36).slice(2,10)}`;
const load=()=>{try{return JSON.parse(localStorage.getItem(DB_KEY))||{};}catch{return {};}};
const save=db=>localStorage.setItem(DB_KEY,JSON.stringify(db));
const user=()=>{try{return JSON.parse(localStorage.getItem(SESSION_KEY));}catch{return null;}};
const isAdmin=()=>user()?.role==='admin';
const canEdit=()=>isAdmin()||(user()?.permissions||[]).includes('warehouse.edit');
const getDb=()=>{const db=load();db.warehouses||=[];db.boxes||=[];db.nomenclature||=[];db.inventory||=[];return db;};
let activeId=null,step=1,dragging=null,resizing=null;

function render(){const page=document.querySelector('#page'),heading=document.querySelector('header h1');if(!page||!heading||heading.textContent.trim()!=='Склад FBS')return false;const db=getDb();if(!activeId||!db.warehouses.some(w=>w.id===activeId))activeId=db.warehouses[0]?.id||null;page.innerHTML=db.warehouses.length?warehouseView(db,db.warehouses.find(w=>w.id===activeId)):emptyView();bind(page);return true;}
function emptyView(){return `<div class="warehouse-empty card"><div class="warehouse-empty-icon">▦</div><h2>Складов пока нет</h2><p>Создайте свой первый склад.</p>${canEdit()?'<button class="primary" id="whCreate">Создать склад</button>':'<p class="muted">Ожидайте, пока менеджер или администратор создаст склад.</p>'}</div>`;}
function warehouseView(db,w){return w.status==='setup'&&canEdit()?wizardView(w):mapView(db,w);}
function warehouseSelector(db){return db.warehouses.length>1?`<select class="warehouse-select wh-select" id="whSelect">${db.warehouses.map(x=>`<option value="${esc(x.id)}" ${x.id===activeId?'selected':''}>${esc(x.name)}</option>`).join('')}</select>`:'';}
function wizardView(w){const steps=['Комната склада','Вход и элементы','Рабочие пространства','Зоны хранения'];const desc=['Создайте контур помещения. Прямоугольник создаёт четыре стены, линия используется для внутренних стен.','Укажите вход на склад. Вход обязателен; при необходимости добавьте окна, ворота и перегородки.','Разместите рабочее пространство сборщиков, зону упаковки, место пустых коробов и место для мусора.','Проверьте планировку. Финальное сохранение зафиксирует помещение. Для изменений используйте «Изменить планировку».'];const elements=(w.elements||[]).filter(e=>e.step<=step);const controls=step===1?`<button class="wh-tool" data-add-el="rect">□ Внешние стены</button><button class="wh-tool" data-add-el="line">╱ Внутренняя стена</button>`:step===2?`<button class="wh-tool" data-add-el="entrance">＋ Вход</button><button class="wh-tool" data-add-el="window">□ Окно</button><button class="wh-tool" data-add-el="gate">▣ Ворота</button><button class="wh-tool" data-add-el="partition">│ Перегородка</button>`:step===3?`<button class="wh-tool" data-add-el="picking">Сборка</button><button class="wh-tool" data-add-el="packing">Упаковка</button><button class="wh-tool" data-add-el="empty-boxes">Пустые короба</button><button class="wh-tool" data-add-el="trash">Мусор</button>`:`<div class="wh-hint">Финальное сохранение зафиксирует планировку.</div>`;return `<div class="wh-wizard"><div class="wh-stepper">${steps.map((s,i)=>`<div class="wh-step ${step===i+1?'current':''} ${step>i+1?'done':''}"><b>${i+1}</b><span>${s}</span></div>`).join('')}</div><div class="card wh-wizard-card"><div class="wh-wizard-head"><div><div class="eyebrow">Склад · ${esc(w.name)}</div><h2>Шаг ${step}. ${steps[step-1]}</h2><p class="muted">${desc[step-1]}</p></div><div class="wh-head-actions">${warehouseSelector(getDb())}<button class="secondary" id="whRename">Переименовать</button></div></div><div class="wh-canvas" data-canvas="wizard"><div class="wh-grid"></div>${elements.map(e=>elementHtml(e,e.step!==step)).join('')}</div><div class="wh-tools">${controls}</div><div class="wh-wizard-actions">${step>1?'<button class="secondary" id="whPrev">Назад</button>':''}${step<4?'<button class="primary" id="whNext">Продолжить</button>':'<button class="primary" id="whFinish">Сохранить планировку</button>'}</div></div></div>`;}
function elementHtml(e,locked){const tools=locked?'':`<button class="wh-delete" data-delete-el="${esc(e.id)}" title="Удалить">×</button><button class="wh-rotate" data-rotate-el="${esc(e.id)}" title="Повернуть">↻</button><i class="wh-resize" data-resize-el="${esc(e.id)}"></i>`;return `<div class="wh-element ${esc(e.type)} ${locked?'locked':''}" data-element-id="${esc(e.id)}" data-element-step="${e.step}" style="left:${e.x}%;top:${e.y}%;width:${e.w}%;height:${e.h}%;transform:rotate(${Number(e.rotation||0)}deg)"><span>${locked&&['rect','line','entrance'].includes(e.type)?'':esc(e.label)}</span>${tools}</div>`;}
function mapView(db,w){const zones=w.zones||[],boxes=db.boxes.filter(b=>b.warehouseId===w.id),edit=canEdit();const work=(w.elements||[]).filter(e=>['picking','packing'].includes(e.type));const combined=combineWorkspaces(work);return `<div class="wh-toolbar card"><div><div class="eyebrow">Склад FBS</div><h2>${esc(w.name)}</h2><span class="muted">${zones.length} зон · ${boxes.length} коробов</span></div><div class="wh-toolbar-actions">${warehouseSelector(db)}${edit?'<button class="secondary" id="whAddWarehouse">＋ Новый склад</button><button class="secondary" id="whEditPlan">Изменить планировку</button><button class="secondary" id="whAddBox">＋ Добавить ящик</button><button class="primary" id="whAddZone">＋ Разместить зону</button>':''}${isAdmin()?'<button class="danger-button" id="whDeleteWarehouse">Удалить склад</button>':''}</div></div><div class="warehouse-layout wh-layout"><div class="map card wh-map"><div class="wh-grid"></div><div class="wh-map-title">${esc(w.name)}</div>${(w.elements||[]).filter(e=>!['picking','packing'].includes(e.type)).map(e=>elementHtml(e,true)).join('')}${combined.map(workspaceHtml).join('')}${zones.map(zoneHtml).join('')}${boxes.map(boxHtml).join('')}</div><aside class="side-panel card wh-side"><h3>Склад</h3><div class="stat"><b>${zones.length}</b><span>зон</span></div><div class="stat"><b>${boxes.length}</b><span>ящиков</span></div><div class="stat"><b>${boxes.filter(b=>!b.zoneId).length}</b><span>без зоны</span></div><hr><h3>Зоны хранения</h3>${zones.length?zones.map(z=>`<div class="wh-zone-row"><div><b>${esc(z.name)}</b><small>${z.boxIds?.length||0} / ${z.capacity} ящиков</small></div>${edit?`<button class="icon-button" data-zone-edit="${esc(z.id)}">⋯</button>`:''}</div>`).join(''):'<p class="muted">Зоны пока не созданы.</p>'}</aside></div>`;}
function combineWorkspaces(items){const out=[],used=new Set();for(const a of items){if(used.has(a.id))continue;const group=[a];for(const b of items){if(b.id===a.id||used.has(b.id))continue;if(overlap(a,b)){group.push(b);used.add(b.id);}}used.add(a.id);const x=Math.min(...group.map(e=>e.x)),y=Math.min(...group.map(e=>e.y)),r=Math.max(...group.map(e=>e.x+e.w)),bt=Math.max(...group.map(e=>e.y+e.h));out.push({x,y,w:r-x,h:bt-y,labels:group.map(e=>e.label)});}return out;}
function overlap(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;}
function workspaceHtml(e){return `<div class="wh-workspace" style="left:${e.x}%;top:${e.y}%;width:${e.w}%;height:${e.h}%"><span>${esc(e.labels.join(' · '))}</span></div>`;}
function zoneHtml(z){return `<div class="wh-zone" data-zone-id="${esc(z.id)}" style="left:${z.x}%;top:${z.y}%;width:${z.w}%;height:${z.h}%"><b>${esc(z.name)}</b><span>${z.boxIds?.length||0}/${z.capacity}</span><i class="wh-resize" data-resize-zone="${esc(z.id)}"></i></div>`;}
function boxHtml(b){const c=b.contents?.[0];let x=4,y=5;if(b.zoneId){const zone=getDb().warehouses.find(w=>w.id===activeId)?.zones?.find(q=>q.id===b.zoneId);if(zone){const i=(zone.boxIds||[]).indexOf(b.id);x=zone.x+Math.min(Math.max(zone.w-8,1),3+(i%4)*7);y=zone.y+Math.min(Math.max(zone.h-7,1),4+Math.floor(i/4)*8);}}return `<div class="wh-box-marker" style="left:${x}%;top:${y}%" title="${esc(c?.article||'Ящик')} / ${esc(c?.size||'')}">▣</div>`;}
function bind(page){page.querySelector('#whCreate')?.addEventListener('click',createWarehouse);page.querySelector('#whAddWarehouse')?.addEventListener('click',createWarehouse);page.querySelector('#whDeleteWarehouse')?.addEventListener('click',deleteWarehouse);page.querySelector('#whSelect')?.addEventListener('change',e=>{activeId=e.target.value;step=1;render();});page.querySelector('#whRename')?.addEventListener('click',renameWarehouse);page.querySelector('#whPrev')?.addEventListener('click',()=>{step=Math.max(1,step-1);render();});page.querySelector('#whNext')?.addEventListener('click',()=>{step=Math.min(4,step+1);render();});page.querySelector('#whFinish')?.addEventListener('click',finish);page.querySelector('#whEditPlan')?.addEventListener('click',()=>{step=1;const db=getDb(),w=db.warehouses.find(x=>x.id===activeId);if(w){w.status='setup';w.editingStartedAt=Date.now();save(db);render();}});page.querySelector('#whAddZone')?.addEventListener('click',addZone);page.querySelector('#whAddBox')?.addEventListener('click',addBox);page.querySelectorAll('[data-add-el]').forEach(b=>b.addEventListener('click',()=>addElement(b.dataset.addEl)));page.querySelectorAll('[data-delete-el]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();deleteElement(b.dataset.deleteEl);}));page.querySelectorAll('[data-rotate-el]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();rotateElement(b.dataset.rotateEl);}));page.querySelectorAll('[data-zone-edit]').forEach(b=>b.addEventListener('click',()=>editZone(b.dataset.zoneEdit)));bindDrag(page);bindResize(page);}
function createWarehouse(){if(!canEdit())return;const db=getDb();const name=prompt('Название нового склада',`Склад №${db.warehouses.length+1}`)?.trim();if(!name)return;if(db.warehouses.some(w=>w.name.toLowerCase()===name.toLowerCase())){alert('Склад с таким названием уже существует.');return;}const w={id:uid('wh'),name,status:'setup',elements:[],zones:[],createdAt:Date.now(),updatedAt:Date.now()};db.warehouses.push(w);save(db);activeId=w.id;step=1;render();}
function deleteWarehouse(){if(!isAdmin())return;const db=getDb(),w=db.warehouses.find(x=>x.id===activeId);if(!w)return;const boxes=db.boxes.filter(b=>b.warehouseId===w.id);const inventory=db.inventory.filter(r=>r.warehouseId===w.id&&Number(r.quantity)>0);if(boxes.length||inventory.length){alert(`Нельзя удалить склад «${w.name}».\n\nНа складе есть изделия (${inventory.reduce((s,r)=>s+Number(r.quantity||0),0)} шт.).\nСначала верните изделия в учет и освободите склад.`);return;}if(!confirm(`Удалить склад «${w.name}»?\n\nДействие нельзя отменить.`))return;db.warehouses=db.warehouses.filter(x=>x.id!==w.id);db.boxes=db.boxes.filter(b=>b.warehouseId!==w.id);db.inventory=db.inventory.filter(r=>r.warehouseId!==w.id);save(db);activeId=db.warehouses[0]?.id||null;step=1;render();}
function renameWarehouse(){const db=getDb(),w=db.warehouses.find(x=>x.id===activeId);if(!w)return;const name=prompt('Название склада',w.name)?.trim();if(name){w.name=name;w.updatedAt=Date.now();save(db);render();}}
function addElement(type){const db=getDb(),w=db.warehouses.find(x=>x.id===activeId);if(!w||w.status!=='setup'||!canEdit())return;const labels={rect:'Стены',line:'Внутренняя стена',entrance:'Вход',window:'Окно',gate:'Ворота',partition:'Перегородка',picking:'Сборка',packing:'Упаковка','empty-boxes':'Пустые короба',trash:'Мусор'};if(type==='entrance'&&(w.elements||[]).some(e=>e.type==='entrance')){alert('На складе уже указан вход.');return;}w.elements||=[];const n=w.elements.length,isLine=type==='line';w.elements.push({id:uid('el'),type,label:labels[type],step,x:Math.min(70,8+(n%5)*5),y:Math.min(70,8+(n%6)*4),w:isLine?32:24,h:isLine?3:24,rotation:0});w.updatedAt=Date.now();save(db);render();}
function deleteElement(id){const db=getDb(),w=db.warehouses.find(x=>x.id===activeId);if(!w||w.status!=='setup')return;const e=w.elements?.find(x=>x.id===id);if(!e||e.step!==step)return;w.elements=w.elements.filter(x=>x.id!==id);save(db);render();}
function rotateElement(id){const db=getDb(),w=db.warehouses.find(x=>x.id===activeId),e=w?.elements?.find(x=>x.id===id);if(!w||w.status!=='setup'||!e||e.step!==step)return;e.rotation=(Number(e.rotation||0)+15)%360;save(db);render();}
function finish(){const db=getDb(),w=db.warehouses.find(x=>x.id===activeId);if(!w)return;if(!(w.elements||[]).some(e=>e.type==='entrance')){alert('Добавьте вход на шаге 2. Вход является обязательным.');step=2;render();return;}if(!(w.elements||[]).some(e=>e.type==='rect'||e.type==='line')){alert('Сначала создайте помещение на шаге 1.');step=1;render();return;}w.status='ready';w.lockedAt=Date.now();w.updatedAt=Date.now();save(db);render();}
function addZone(){const db=getDb(),w=db.warehouses.find(x=>x.id===activeId);if(!w||!canEdit())return;const name=prompt('Название зоны',`Зона ${String.fromCharCode(65+(w.zones?.length||0))}`)?.trim();if(!name)return;const capacity=Number(prompt('Вместимость зоны в коробах или ящиках','10'));if(!Number.isInteger(capacity)||capacity<1){alert('Введите положительное целое число.');return;}w.zones||=[];const n=w.zones.length;w.zones.push({id:uid('zone'),name,capacity,boxIds:[],x:8+(n%4)*23,y:24+Math.floor(n/4)*28,w:20,h:20});w.updatedAt=Date.now();save(db);render();}
function editZone(id){const db=getDb(),w=db.warehouses.find(x=>x.id===activeId),z=w?.zones?.find(x=>x.id===id);if(!z||!canEdit())return;const name=prompt('Название зоны',z.name)?.trim();if(!name)return;const capacity=Number(prompt('Вместимость зоны',z.capacity));if(!Number.isInteger(capacity)||capacity<z.boxIds.length){alert(`Вместимость не может быть меньше ${z.boxIds.length}.`);return;}z.name=name;z.capacity=capacity;save(db);render();}
function addBox(){const db=getDb(),w=db.warehouses.find(x=>x.id===activeId);if(!w||!canEdit())return;const available=db.nomenclature||[];if(!available.length){alert('Сначала загрузите номенклатуру в разделе «Учет номенклатуры».');return;}const options=available.slice(0,120).map((n,i)=>`${i+1}. ${n.article} / ${n.size} / ${n.barcode}`).join('\n');const selected=prompt(`Выберите изделие по номеру:\n\n${options}\n\n0 — отмена`,'1')?.trim();if(!selected)return;const index=Number(selected)-1;if(!Number.isInteger(index)||!available[index]){if(selected!=='0')alert('Некорректный номер изделия.');return;}const item=available[index],quantity=Number(prompt(`Количество для «${item.article} / ${item.size}»`,'1'));if(!Number.isInteger(quantity)||quantity<1){alert('Количество должно быть положительным целым числом.');return;}const zoneId=chooseZone(w);if(zoneId===false)return;const box={id:uid('box'),name:`Ящик ${String(db.boxes.length+1).padStart(4,'0')}`,qr:`BJOB-${String(db.boxes.length+1).padStart(6,'0')}`,warehouseId:w.id,zoneId:zoneId||null,contents:[{barcode:item.barcode,article:item.article,size:item.size,quantity}],createdAt:Date.now()};db.boxes.push(box);w.zones||=[];if(zoneId){const z=w.zones.find(x=>x.id===zoneId);z.boxIds||=[];z.boxIds.push(box.id);}rebuildInventory(db,w.id);save(db);render();}
function chooseZone(w){const zones=w.zones||[];if(!zones.length)return null;const list=zones.map((z,i)=>`${i+1}. ${z.name} (${z.boxIds?.length||0}/${z.capacity})`).join('\n');const answer=prompt(`Выберите зону для ящика:\n\n${list}\n\n0 — без зоны`,'1');if(answer===null)return false;const n=Number(answer);if(n===0)return null;const z=zones[n-1];if(!z){alert('Некорректная зона.');return false;}if((z.boxIds?.length||0)>=z.capacity){alert('Зона заполнена.');return false;}return z.id;}
function rebuildInventory(db,warehouseId){db.inventory=db.inventory.filter(row=>row.warehouseId!==warehouseId);const boxes=db.boxes.filter(b=>b.warehouseId===warehouseId),w=db.warehouses.find(x=>x.id===warehouseId);for(const box of boxes){const zone=w?.zones?.find(z=>z.id===box.zoneId);for(const c of box.contents||[]){const key=`${c.barcode}|${box.zoneId||''}`;let row=db.inventory.find(r=>r.warehouseId===warehouseId&&r._key===key);if(!row){row={_key:key,warehouseId,barcode:c.barcode,article:c.article,size:c.size,zone:zone?.name||'Без зоны',quantity:0};db.inventory.push(row);}row.quantity+=Number(c.quantity)||0;}}}
function bindDrag(page){const canvas=page.querySelector('[data-canvas]')||page.querySelector('.wh-map');if(!canvas)return;page.querySelectorAll('[data-element-id]').forEach(el=>{if(Number(el.dataset.elementStep)!==step||el.classList.contains('locked'))return;makeDraggable(el,canvas,'element');});page.querySelectorAll('[data-zone-id]').forEach(el=>makeDraggable(el,canvas,'zone'));}
function makeDraggable(el,canvas,kind){if(el.dataset.dragBound)return;el.dataset.dragBound='1';el.addEventListener('pointerdown',event=>{if(event.target.closest('button')||event.target.classList.contains('wh-resize'))return;event.preventDefault();el.setPointerCapture?.(event.pointerId);const r=canvas.getBoundingClientRect();dragging={el,canvas,kind,startX:event.clientX,startY:event.clientY,sx:parseFloat(el.style.left),sy:parseFloat(el.style.top),rect:r};});el.addEventListener('pointermove',event=>{if(!dragging||dragging.el!==el)return;const dx=(event.clientX-dragging.startX)/dragging.rect.width*100,dy=(event.clientY-dragging.startY)/dragging.rect.height*100;const w=parseFloat(el.style.width),h=parseFloat(el.style.height);el.style.left=`${Math.max(0,Math.min(100-w,dragging.sx+dx))}%`;el.style.top=`${Math.max(0,Math.min(100-h,dragging.sy+dy))}%`;});el.addEventListener('pointerup',()=>{if(!dragging||dragging.el!==el)return;persistPosition(el,kind);dragging=null;});}
function bindResize(page){page.querySelectorAll('[data-resize-el],[data-resize-zone]').forEach(handle=>{if(handle.dataset.resizeBound)return;handle.dataset.resizeBound='1';handle.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();const el=handle.parentElement,canvas=el.closest('.wh-canvas,.wh-map');if(!canvas)return;resizing={handle,el,canvas,startX:e.clientX,startY:e.clientY,startW:parseFloat(el.style.width),startH:parseFloat(el.style.height),rect:canvas.getBoundingClientRect()};handle.setPointerCapture?.(e.pointerId);});handle.addEventListener('pointermove',e=>{if(!resizing||resizing.handle!==handle)return;const dw=(e.clientX-resizing.startX)/resizing.rect.width*100,dh=(e.clientY-resizing.startY)/resizing.rect.height*100;resizing.el.style.width=`${Math.max(3,Math.min(96,resizing.startW+dw))}%`;resizing.el.style.height=`${Math.max(2,Math.min(96,resizing.startH+dh))}%`;});handle.addEventListener('pointerup',()=>{if(!resizing||resizing.handle!==handle)return;persistPosition(resizing.el,resizing.el.dataset.zoneId?'zone':'element');resizing=null;});});}
function persistPosition(el,kind){const db=getDb(),w=db.warehouses.find(x=>x.id===activeId);if(!w)return;const id=kind==='zone'?el.dataset.zoneId:el.dataset.elementId;const item=kind==='zone'?w.zones?.find(x=>x.id===id):w.elements?.find(x=>x.id===id);if(!item)return;item.x=parseFloat(el.style.left);item.y=parseFloat(el.style.top);item.w=parseFloat(el.style.width);item.h=parseFloat(el.style.height);w.updatedAt=Date.now();save(db);}
const observer=new MutationObserver(()=>{const heading=document.querySelector('header h1');const page=document.querySelector('#page');if(heading?.textContent.trim()==='Склад FBS'&&page){if(!page.querySelector('.warehouse-empty,.wh-wizard,.wh-toolbar'))render();}});observer.observe(document.documentElement,{childList:true,subtree:true});setTimeout(render,0);
